import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { headers } from "next/headers"

import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { type Locale, defaultLocale, getDirectionForLocale, isLocale } from "@/lib/i18n"
import { cn } from "@/lib/utils"

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
})

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

export const metadata: Metadata = {
  title: "stashy-ui",
  description: "Starter app generated by Forge for stashy-ui.",
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    title: "stashy-ui",
    description: "Starter app generated by Forge for stashy-ui.",
    type: "website",
    locale: "en_US",
    alternateLocale: "ar_AR",
  },
  twitter: {
    card: "summary_large_image",
    title: "stashy-ui",
    description: "Starter app generated by Forge for stashy-ui.",
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const requestHeaders = await headers()
  const headerLocale = requestHeaders.get("x-forge-locale") ?? undefined
  const initialLocale: Locale = isLocale(headerLocale) ? headerLocale : defaultLocale
  const initialDirection = getDirectionForLocale(initialLocale)

  return (
    <html lang={initialLocale} dir={initialDirection} suppressHydrationWarning>
      <body
        className={cn("antialiased", "font-sans", geist.variable, fontMono.variable)}
        suppressHydrationWarning
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
