import type { AnalyticsMonth } from "@/components/analytics/types"

export const ANALYTICS_PLAN: "free" | "pro" = "pro"

export const analyticsMonths: AnalyticsMonth[] = [
  {
    id: "2026-02",
    isoDate: "2026-02-01",
    daysTracked: 28,
    daysRemaining: 0,
    status: "closed",
    pacingDeltaPct: 4,
    budgetUsedPct: 100,
    monthProgressPct: 100,
    overspentDaysMtd: 6,
    avgDailySpend: 189,
    projectedEndSpend: 5320,
    projectedSavings: 680,
    projectedSavingsRate: 11,
    effectiveBudget: 6000,
    totalVariableSpent: 1480,
    incomeReceived: 0,
    fixedOverspend: 140,
    majorPurchasesTotal: 2400,
    fixedTotalBudget: 1640,
    fixedTotalSpent: 1780,
    fixedManualOverBudgetCount: 2,
    fixedAutoPaidCount: 2,
    fixedAutoTotalCount: 2,
    majorPurchaseCount: 3,
    savingsRate: 11,
    baseDailyRate: 278,
    largePurchasesPct: 17,
  },
  {
    id: "2026-03",
    isoDate: "2026-03-01",
    daysTracked: 31,
    daysRemaining: 0,
    status: "closed",
    pacingDeltaPct: -5,
    budgetUsedPct: 94,
    monthProgressPct: 100,
    overspentDaysMtd: 2,
    avgDailySpend: 173,
    projectedEndSpend: 5360,
    projectedSavings: 940,
    projectedSavingsRate: 18,
    effectiveBudget: 6000,
    totalVariableSpent: 860,
    incomeReceived: 200,
    fixedOverspend: 0,
    majorPurchasesTotal: 720,
    fixedTotalBudget: 1640,
    fixedTotalSpent: 1540,
    fixedManualOverBudgetCount: 0,
    fixedAutoPaidCount: 2,
    fixedAutoTotalCount: 2,
    majorPurchaseCount: 2,
    savingsRate: 18,
    baseDailyRate: 278,
    largePurchasesPct: 12,
  },
  {
    id: "2026-04",
    isoDate: "2026-04-01",
    daysTracked: 25,
    daysRemaining: 5,
    status: "inProgress",
    pacingDeltaPct: -12,
    budgetUsedPct: 36,
    monthProgressPct: 81,
    overspentDaysMtd: 3,
    avgDailySpend: 160,
    projectedEndSpend: 4960,
    projectedSavings: 1040,
    projectedSavingsRate: 17,
    effectiveBudget: 6000,
    totalVariableSpent: 700,
    incomeReceived: 300,
    fixedOverspend: 260,
    majorPurchasesTotal: 2400,
    fixedTotalBudget: 1640,
    fixedTotalSpent: 1900,
    fixedManualOverBudgetCount: 1,
    fixedAutoPaidCount: 2,
    fixedAutoTotalCount: 2,
    majorPurchaseCount: 2,
    savingsRate: 24,
    baseDailyRate: 278,
    largePurchasesPct: 8,
  },
]

export const FILL_WIDTH_CLASS = {
  36: "w-[36%]",
  94: "w-[94%]",
  100: "w-[100%]",
} as const

export const TICK_POSITION_CLASS = {
  81: "start-[81%]",
  100: "start-[100%]",
} as const
